---
version: '3.4'

services:
  db-test:
    env_file:
      - docker/.env-db
    image: "postgres:14.2-alpine"
    volumes:
      - db-data-test:/var/lib/postgresql/data

  web-test:
    build:
      dockerfile: docker/Dockerfile
      context: .
      target: django-dev
    env_file:
      - docker/.env-web
    depends_on:
      - db-test

volumes:
  db-data-test:
