---
version: '3.4'

services:
  db:
    image: "postgres:14.2-alpine"

  web:
    build:
      dockerfile: docker/Dockerfile
      context: .
      target: django
    command: python manage.py runserver 0.0.0.0:80
    depends_on:
      - db

volumes:
  db-data:
